apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.fareEstimation.releaseName}}-config
data:
  FARE_ESTIMATION_PORT: {{ .Values.fareEstimation.image.port | quote }}

  DB_HOST: {{ .Values.global.database.postgres.DB_HOST | quote }}
  DB_PORT: {{ .Values.global.database.postgres.DB_PORT | quote }}
  DB_NAME: {{ .Values.global.database.postgres.DB_NAME | quote }}
  DB_USER: {{ .Values.global.database.postgres.DB_USER | quote }}

  KAFKA_BROKERS: {{.Values.kafka.BROKERS | quote }}
  KAFKA_CLIENT_ID: {{.Values.kafka.CLIENT_ID | quote }}
  KAFKA_GROUP_ID: {{.Values.kafka.GROUP_ID | quote }}
  KAFKA_ESTIMATE_REQUEST_TOPIC: {{.Values.kafka.ESTIMATE_REQUEST_TOPIC | quote }}
  KAFKA_TRIP_REQUEST_TOPIC: {{.Values.kafka.TRIP_REQUEST_TOPIC | quote }}
  KAFKA_NOTIFICATION_TOPIC: {{.Values.kafka.NOTIFICATION_TOPIC | quote }}

  FARE_BASE_FARE: {{.Values.fareEstimation.fare.BASE_FARE | quote }}
  FARE_TIME_RATE: {{.Values.fareEstimation.fare.TIME_RATE | quote }}
  FARE_DISTANCE_RATE: {{.Values.fareEstimation.fare.DISTANCE_RATE | quote }}
  FARE_SURGE_MULTIPLIER: {{.Values.fareEstimation.fare.SURGE_MULTIPLIER | quote }}
  FARE_CURRENCY: {{.Values.fareEstimation.fare.CURRENCY | quote }}
  FARE_FALLBACK_AVERAGE_SPEED_KPH: {{.Values.fareEstimation.fare.FALLBACK_AVERAGE_SPEED_KPH | quote }}
