apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fareEstimation.releaseName }}-service
  labels:
    app: {{ .Values.fareEstimation.releaseName }}-app
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.fareEstimation.releaseName }}-app
  ports:
    - protocol: TCP
      port: {{ .Values.fareEstimation.service.port }}
      targetPort: {{ .Values.fareEstimation.service.targetPort }}