apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kafka.releaseName }}-service
  labels:
    app: {{ .Values.kafka.releaseName }}-app
spec:
  clusterIP: None
  selector:
    app: {{ .Values.kafka.releaseName }}-app
  ports:
    - name: broker
      protocol: TCP
      port: {{ .Values.kafka.service.port }}
      targetPort: {{ .Values.kafka.service.targetPort }}
    - name: controller
      protocol: TCP
      port: {{ .Values.kafka.service.controllerPort }}
      targetPort: {{ .Values.kafka.service.controllerTargetPort }}
