apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.kafka.releaseName }}-statefulset
  labels:
    app: {{ .Values.kafka.releaseName }}-app
spec:
  serviceName: {{ .Values.kafka.releaseName }}-service
  replicas: {{ .Values.kafka.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.kafka.releaseName }}-app
  template:
    metadata:
      labels:
        app: {{ .Values.kafka.releaseName }}-app
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configMap.kafka.yml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Values.kafka.releaseName }}-container
          image: {{ .Values.kafka.image.name }}:{{ .Values.kafka.image.tag }}
          imagePullPolicy: {{ .Values.kafka.image.pullPolicy }}
          ports:
            - name: broker
              containerPort: {{ .Values.kafka.service.port }}
            - name: controller
              containerPort: {{ .Values.kafka.service.controllerPort }}
          env:
            - name: KAFKA_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KAFKA_PROCESS_ROLES
              value: {{ .Values.kafka.configuration.KAFKA_PROCESS_ROLES }}
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: {{ .Values.kafka.configuration.KAFKA_CONTROLLER_QUORUM_VOTERS }}
            - name: KAFKA_LISTENERS
              value: {{ .Values.kafka.configuration.KAFKA_LISTENERS }}
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: {{ .Values.kafka.configuration.LISTENER_SECURITY_PROTOCOL_MAP }}
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: {{ .Values.kafka.configuration.KAFKA_CONTROLLER_LISTENER_NAMES }}
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: CLUSTER_NAME
              value: "{{ .Values.kafka.clusterName }}"
            - name: CLUSTER_ID
              value: {{ .Values.kafka.configuration.CLUSTER_ID }}
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"

          command:
            - sh
            - -c
            - |
              # Extract numeric index from pod name (e.g., kafka-0 -> 0)
              export KAFKA_NODE_ID=$(echo $KAFKA_NODE_ID | awk -F'-' '{print $NF}')
              # Generate advertised listeners dynamically per pod using full pod hostname
              export KAFKA_ADVERTISED_LISTENERS="PLAINTEXT://${HOSTNAME}.{{ .Values.kafka.releaseName }}-service.{{ .Values.cluster.namespace }}.svc.cluster.local:9092"
              exec /etc/confluent/docker/run
  volumeClaimTemplates:
    - metadata:
        name: kafka-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi