apiVersion: v1
kind: Service # ServiceTypes allow you to specify what kind of Service you want
metadata:
  name: {{ .Values.apiGateway.releaseName }}-service
  labels:
    app: {{ .Values.apiGateway.releaseName }}-app
spec:
  selector:
    app: {{ .Values.apiGateway.releaseName }}-app # This selector will match the labels of the pods that this service should route traffic to
  # This service will be accessible from outside the cluster.
  ports:
    - protocol: TCP
      port: {{ .Values.apiGateway.service.port }} # external port that the service will expose
      targetPort: {{ .Values.apiGateway.service.targetPort }} # internal port on the pod that the service will forward traffic to
  type: {{ .Values.apiGateway.service.type }}